services:
  db:
    image: postgres:16
    container_name: db
    restart: always
    environment:
      POSTGRES_DB: pool_appointments
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - nine-line-net

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - nine-line-net

  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    container_name: api
    env_file:
      - ./apps/api/.env
    ports:
      - "3333:3333"
      - "5555:5555"
    depends_on:
      - db
      - redis
    networks:
      - nine-line-net

  backoffice:
    build:
      context: .
      dockerfile: ./apps/backoffice/Dockerfile
    container_name: backoffice
    env_file:
      - ./apps/backoffice/.env
    ports:
      - "3001:3001"
    depends_on:
      - api
    networks:
      - nine-line-net

  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    container_name: web
    environment:
      - NEXT_PUBLIC_API_URL=http://api:3333/api
      - NEXT_PUBLIC_APP_NAME=Nine Line Web
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - nine-line-net

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./packages/config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./packages/config/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - api
      - backoffice
      - web
    networks:
      - nine-line-net

volumes:
  db_data:

networks:
  nine-line-net:
    driver: bridge 