import {
  LayoutDashboard as LayoutDashboardIcon,
  Users as UsersIcon,
  Settings as SettingsIcon,
  BarChart3 as BarChart3Icon,
  FileText as FileTextIcon,
  User as UserIcon,
  Bell as BellIcon,
  Menu as MenuIcon,
  X as XIcon,
  ChevronRight as ChevronRightIcon,
  Home as HomeIcon,
  FolderOpen as FolderOpenIcon,
  TrendingUp as TrendingUpIcon,
  AlertTriangle as AlertTriangleIcon,
  CheckCircle as CheckCircleIcon,
  Clock as ClockIcon,
  Plus as PlusIcon,
  Search as SearchIcon,
  Filter as FilterIcon,
  MoreHorizontal as MoreHorizontalIcon,
  Edit as EditIcon,
  Trash2 as Trash2Icon,
  Eye as EyeIcon,
  Download as DownloadIcon,
  Upload as UploadIcon,
  RefreshCw as RefreshCwIcon,
  Calendar as CalendarIcon,
  Mail as MailIcon,
  Phone as PhoneIcon,
  MapPin as MapPinIcon,
  Globe as GlobeIcon,
  Lock as LockIcon,
  Unlock as UnlockIcon,
  Key as KeyIcon,
  Shield as ShieldIcon,
  Zap as ZapIcon,
  Star as StarIcon,
  Heart as HeartIcon,
  ThumbsUp as ThumbsUpIcon,
  ThumbsDown as ThumbsDownIcon,
  MessageSquare as MessageSquareIcon,
  Share2 as Share2Icon,
  Copy as CopyIcon,
  Link as LinkIcon,
  ExternalLink as ExternalLinkIcon,
  ArrowRight as ArrowRightIcon,
  ArrowLeft as ArrowLeftIcon,
  ArrowUp as ArrowUpIcon,
  ArrowDown as ArrowDownIcon,
  ChevronUp as ChevronUpIcon,
  ChevronDown as ChevronDownIcon,
  ChevronLeft as ChevronLeftIcon,
  Minus as MinusIcon,
  Check as CheckIcon,
  AlertCircle as AlertCircleIcon,
  Info as InfoIcon,
  HelpCircle as HelpCircleIcon,
  Camera as CameraIcon,
  Image as ImageIcon,
  Video as VideoIcon,
  Music as MusicIcon,
  File as FileIcon,
  Folder as FolderIcon,
  Archive as ArchiveIcon,
  Book as BookIcon,
  BookOpen as BookOpenIcon,
  Newspaper as NewspaperIcon,
  FileCode as FileCodeIcon,
  Code as CodeIcon,
  Database as DatabaseIcon,
  Server as ServerIcon,
  Cloud as CloudIcon,
  Wifi as WifiIcon,
  Bluetooth as BluetoothIcon,
  Monitor as MonitorIcon,
  Smartphone as SmartphoneIcon,
  Tablet as TabletIcon,
  Laptop as LaptopIcon,
  Printer as PrinterIcon,
  Keyboard as KeyboardIcon,
  Mouse as MouseIcon,
  Headphones as HeadphonesIcon,
  Speaker as SpeakerIcon,
  Mic as MicIcon,
  Volume as VolumeIcon,
  Volume1 as Volume1Icon,
  Volume2 as Volume2Icon,
  VolumeX as VolumeXIcon,
  Play as PlayIcon,
  Pause as PauseIcon,
  Square as SquareIcon,
  SkipBack as SkipBackIcon,
  SkipForward as SkipForwardIcon,
  FastForward as FastForwardIcon,
  Rewind as RewindIcon,
  Shuffle as ShuffleIcon,
  Repeat as RepeatIcon,
  Repeat1 as Repeat1Icon,
  Package as PackageIcon,
  Truck as TruckIcon,
  ShoppingCart as ShoppingCartIcon,
  Store as StoreIcon,
  DollarSign as DollarSignIcon,
  TrendingDown as TrendingDownIcon,
  LogOut as LogOutIcon,
} from "lucide-react";

export const getIconComponent = (
  iconName: string,
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
): React.ComponentType<any> => {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const iconMap: Record<string, React.ComponentType<any>> = {
    dashboard: LayoutDashboardIcon,
    users: UsersIcon,
    settings: SettingsIcon,
    analytics: BarChart3Icon,
    reports: FileTextIcon,
    team: UsersIcon,
    account: UserIcon,
    bell: BellIcon,
    menu: MenuIcon,
    close: XIcon,
    "chevron-right": ChevronRightIcon,
    home: HomeIcon,
    "folder-open": FolderOpenIcon,
    "trending-up": TrendingUpIcon,
    alert: AlertTriangleIcon,
    "check-circle": CheckCircleIcon,
    clock: ClockIcon,
    plus: PlusIcon,
    search: SearchIcon,
    filter: FilterIcon,
    more: MoreHorizontalIcon,
    edit: EditIcon,
    delete: Trash2Icon,
    eye: EyeIcon,
    download: DownloadIcon,
    upload: UploadIcon,
    refresh: RefreshCwIcon,
    calendar: CalendarIcon,
    mail: MailIcon,
    phone: PhoneIcon,
    map: MapPinIcon,
    globe: GlobeIcon,
    lock: LockIcon,
    unlock: UnlockIcon,
    key: KeyIcon,
    shield: ShieldIcon,
    zap: ZapIcon,
    star: StarIcon,
    heart: HeartIcon,
    "thumbs-up": ThumbsUpIcon,
    "thumbs-down": ThumbsDownIcon,
    message: MessageSquareIcon,
    share: Share2Icon,
    copy: CopyIcon,
    link: LinkIcon,
    external: ExternalLinkIcon,
    "arrow-right": ArrowRightIcon,
    "arrow-left": ArrowLeftIcon,
    "arrow-up": ArrowUpIcon,
    "arrow-down": ArrowDownIcon,
    "chevron-up": ChevronUpIcon,
    "chevron-down": ChevronDownIcon,
    "chevron-left": ChevronLeftIcon,
    minus: MinusIcon,
    check: CheckIcon,
    "alert-circle": AlertCircleIcon,
    info: InfoIcon,
    help: HelpCircleIcon,
    camera: CameraIcon,
    image: ImageIcon,
    video: VideoIcon,
    music: MusicIcon,
    file: FileIcon,
    folder: FolderIcon,
    archive: ArchiveIcon,
    book: BookIcon,
    "book-open": BookOpenIcon,
    newspaper: NewspaperIcon,
    "file-code": FileCodeIcon,
    code: CodeIcon,
    database: DatabaseIcon,
    server: ServerIcon,
    cloud: CloudIcon,
    wifi: WifiIcon,
    bluetooth: BluetoothIcon,
    monitor: MonitorIcon,
    smartphone: SmartphoneIcon,
    tablet: TabletIcon,
    laptop: LaptopIcon,
    printer: PrinterIcon,
    keyboard: KeyboardIcon,
    mouse: MouseIcon,
    headphones: HeadphonesIcon,
    speaker: SpeakerIcon,
    mic: MicIcon,
    volume: VolumeIcon,
    "volume-1": Volume1Icon,
    "volume-2": Volume2Icon,
    "volume-x": VolumeXIcon,
    play: PlayIcon,
    pause: PauseIcon,
    stop: SquareIcon,
    "skip-back": SkipBackIcon,
    "skip-forward": SkipForwardIcon,
    "fast-forward": FastForwardIcon,
    rewind: RewindIcon,
    shuffle: ShuffleIcon,
    repeat: RepeatIcon,
    "repeat-1": Repeat1Icon,
    package: PackageIcon,
    truck: TruckIcon,
    "shopping-cart": ShoppingCartIcon,
    store: StoreIcon,
    "dollar-sign": DollarSignIcon,
    "trending-down": TrendingDownIcon,
    "log-out": LogOutIcon,
  };

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  return iconMap[iconName] || (UserIcon as React.ComponentType<any>);
};
