export const MOCK_MANAGER_DATA = {
  orders: {
    pending: 23,
    processing: 12,
    completed: 156,
    recentOrders: [
      {
        id: "1247",
        customer: "João Silva",
        amount: 89.5,
        status: "pending" as const,
        time: "2h atrás",
      },
      {
        id: "1246",
        customer: "Maria Santos",
        amount: 156.3,
        status: "processing" as const,
        time: "4h atrás",
      },
      {
        id: "1245",
        customer: "Pedro Costa",
        amount: 67.8,
        status: "completed" as const,
        time: "6h atrás",
      },
      {
        id: "1244",
        customer: "Ana Oliveira",
        amount: 234.9,
        status: "completed" as const,
        time: "8h atrás",
      },
    ],
  },
  inventory: {
    totalItems: 156,
    lowStock: 8,
    outOfStock: 2,
    items: [
      {
        id: "1",
        name: "Arroz Integral",
        quantity: 45,
        minQuantity: 20,
        status: "in_stock" as const,
        lastRestocked: "2 dias atrás",
      },
      {
        id: "2",
        name: "Feijão Preto",
        quantity: 12,
        minQuantity: 15,
        status: "low_stock" as const,
        lastRestocked: "5 dias atrás",
      },
      {
        id: "3",
        name: "Azeite de Oliva",
        quantity: 0,
        minQuantity: 10,
        status: "out_of_stock" as const,
        lastRestocked: "1 semana atrás",
      },
      {
        id: "4",
        name: "Café em Grãos",
        quantity: 8,
        minQuantity: 10,
        status: "low_stock" as const,
        lastRestocked: "3 dias atrás",
      },
    ],
  },
  activities: [
    {
      id: "1",
      type: "order" as const,
      title: "Novo pedido processado",
      description: "Pedido #1246 de Maria Santos",
      time: "2h atrás",
      color: "bg-blue-500",
    },
    {
      id: "2",
      type: "delivery" as const,
      title: "Entrega iniciada",
      description: "Pedido #1244 em rota de entrega",
      time: "4h atrás",
      color: "bg-green-500",
    },
    {
      id: "3",
      type: "stock" as const,
      title: "Reposição de estoque",
      description: "Arroz Integral reabastecido",
      time: "6h atrás",
      color: "bg-yellow-500",
    },
  ],
};
