import { NavigationItem } from "@/core/@types/user.types";

export const DASHBOARD_NAVIGATION: Record<string, NavigationItem[]> = {
  backoffice: [
    {
      id: "dashboard",
      label: "dashboard",
      href: "/backoffice",
      icon: "dashboard",
    },
    {
      id: "markets",
      label: "markets",
      href: "/backoffice/markets",
      icon: "store",
      children: [
        {
          id: "all-markets",
          label: "all-markets",
          href: "/backoffice/markets/all",
          icon: "list",
        },
        {
          id: "add-market",
          label: "add-market",
          href: "/backoffice/markets/add",
          icon: "plus",
        },
        {
          id: "location",
          label: "location",
          href: "/backoffice/markets/location",
          icon: "map-pin",
        },
        {
          id: "performance",
          label: "performance",
          href: "/backoffice/markets/performance",
          icon: "trending-up",
        },
      ],
    },
    {
      id: "products",
      label: "products",
      href: "/backoffice/products",
      icon: "package",
      children: [
        {
          id: "catalog",
          label: "catalog",
          href: "/backoffice/products/catalog",
          icon: "grid",
        },
        {
          id: "stock",
          label: "stock",
          href: "/backoffice/products/stock",
          icon: "database",
        },
        {
          id: "categories",
          label: "categories",
          href: "/backoffice/products/categories",
          icon: "folder",
        },
        {
          id: "prices",
          label: "prices",
          href: "/backoffice/products/prices",
          icon: "dollar-sign",
        },
      ],
    },
    {
      id: "sales",
      label: "sales",
      href: "/backoffice/sales",
      icon: "shopping-cart",
      badge: 12,
      children: [
        {
          id: "orders",
          label: "orders",
          href: "/backoffice/sales/orders",
          icon: "list",
        },
        {
          id: "transactions",
          label: "transactions",
          href: "/backoffice/sales/transactions",
          icon: "credit-card",
        },
        {
          id: "campaigns",
          label: "campaigns",
          href: "/backoffice/sales/campaigns",
          icon: "target",
        },
        {
          id: "promotions",
          label: "promotions",
          href: "/backoffice/sales/promotions",
          icon: "gift",
        },
      ],
    },
    {
      id: "financial",
      label: "financial",
      href: "/backoffice/financial",
      icon: "wallet",
      children: [
        {
          id: "revenue",
          label: "revenue",
          href: "/backoffice/financial/revenue",
          icon: "trending-up",
        },
        {
          id: "expenses",
          label: "expenses",
          href: "/backoffice/financial/expenses",
          icon: "trending-down",
        },
        {
          id: "cash-flow",
          label: "cash-flow",
          href: "/backoffice/financial/cash-flow",
          icon: "activity",
        },
        {
          id: "reports",
          label: "reports",
          href: "/backoffice/financial/reports",
          icon: "file-text",
        },
      ],
    },
    {
      id: "settings",
      label: "settings",
      href: "/backoffice/settings",
      icon: "settings",
    },
  ],
  manager: [
    {
      id: "dashboard",
      label: "dashboard",
      href: "/manager",
      icon: "dashboard",
      isActive: true,
    },
    {
      id: "markets",
      label: "markets",
      href: "/manager/markets",
      icon: "store",
      isBackoffice: true,
      children: [
        {
          id: "all-markets",
          label: "all-markets",
          href: "/manager/markets/all",
          icon: "list",
          isActive: false,
        },
        {
          id: "add-market",
          label: "add-market",
          href: "/manager/markets/add",
          icon: "plus",
          isActive: false,
        },
        {
          id: "location",
          label: "location",
          href: "/manager/markets/location",
          icon: "map-pin",
          isActive: false,
        },
        {
          id: "performance",
          label: "performance",
          href: "/manager/markets/performance",
          icon: "trending-up",
          isActive: false,
        },
      ],
    },
    {
      id: "products",
      label: "products",
      href: "/manager/products",
      icon: "package",
      children: [
        {
          id: "catalog",
          label: "catalog",
          href: "/manager/products/catalog",
          icon: "grid",
          isActive: true,
        },
        {
          id: "stock",
          label: "stock",
          href: "/manager/products/stock",
          icon: "database",
          isActive: true,
        },
        {
          id: "categories",
          label: "categories",
          href: "/manager/products/categories",
          icon: "folder",
          isActive: false,
        },
        {
          id: "prices",
          label: "prices",
          href: "/manager/products/prices",
          icon: "dollar-sign",
          isActive: false,
        },
      ],
    },
    {
      id: "sales",
      label: "sales",
      href: "/manager/sales",
      icon: "shopping-cart",
      badge: 12,
      children: [
        {
          id: "orders",
          label: "orders",
          href: "/manager/sales/orders",
          icon: "list",
          isActive: true,
        },
        {
          id: "transactions",
          label: "transactions",
          href: "/manager/sales/transactions",
          icon: "credit-card",
          isActive: true,
        },
        {
          id: "campaigns",
          label: "campaigns",
          href: "/manager/sales/campaigns",
          icon: "target",
          isActive: false,
        },
        {
          id: "promotions",
          label: "promotions",
          href: "/manager/sales/promotions",
          icon: "gift",
          isActive: false,
        },
      ],
    },
    {
      id: "financial",
      label: "financial",
      href: "/manager/financial",
      icon: "wallet",
      isBackoffice: true,
      children: [
        {
          id: "revenue",
          label: "revenue",
          href: "/manager/financial/revenue",
          icon: "trending-up",
          isActive: false,
        },
        {
          id: "expenses",
          label: "expenses",
          href: "/manager/financial/expenses",
          icon: "trending-down",
          isActive: false,
        },
        {
          id: "cash-flow",
          label: "cash-flow",
          href: "/manager/financial/cash-flow",
          icon: "activity",
          isActive: false,
        },
        {
          id: "reports",
          label: "reports",
          href: "/manager/financial/reports",
          icon: "file-text",
          isActive: false,
        },
      ],
    },
    {
      id: "reports",
      label: "reports",
      href: "/manager/reports",
      icon: "bar-chart-3",
      children: [
        {
          id: "sales-reports",
          label: "sales-reports",
          href: "/manager/reports/sales",
          icon: "trending-up",
          isActive: true,
        },
        {
          id: "markets-reports",
          label: "markets-reports",
          href: "/manager/reports/markets",
          icon: "store",
          isActive: false,
        },
        {
          id: "products-reports",
          label: "products-reports",
          href: "/manager/reports/products",
          icon: "package",
          isActive: false,
        },
        {
          id: "customers-reports",
          label: "customers-reports",
          href: "/manager/reports/customers",
          icon: "users",
          isActive: false,
        },
      ],
    },
    {
      id: "users",
      label: "users",
      href: "/manager/users",
      icon: "users",
      isBackoffice: true,
      children: [
        {
          id: "manage-users",
          label: "manage-users",
          href: "/manager/users/manage",
          icon: "user-plus",
          isActive: false,
        },
        {
          id: "permissions",
          label: "permissions",
          href: "/manager/users/permissions",
          icon: "shield",
          isActive: false,
        },
        {
          id: "teams",
          label: "teams",
          href: "/manager/users/teams",
          icon: "users",
          isActive: false,
        },
      ],
    },
    {
      id: "tools",
      label: "tools",
      href: "/manager/tools",
      icon: "settings",
      children: [
        {
          id: "calendar",
          label: "calendar",
          href: "/manager/tools/calendar",
          icon: "calendar",
          isActive: true,
        },
        {
          id: "notifications",
          label: "notifications",
          href: "/manager/tools/notifications",
          icon: "bell",
          isActive: true,
        },
        {
          id: "documents",
          label: "documents",
          href: "/manager/tools/documents",
          icon: "file-text",
          isActive: true,
        },
        {
          id: "help",
          label: "help",
          href: "/manager/tools/help",
          icon: "help-circle",
          isActive: true,
        },
        {
          id: "settings",
          label: "settings",
          href: "/manager/tools/settings",
          icon: "settings",
          isActive: true,
        },
      ],
    },
  ],
};

export const MOCK_MARKET_STATS = {
  totalOrders: 1247,
  pendingOrders: 47,
  totalRevenue: 125000,
  monthlyGrowth: 18.5,
  lowStockItems: 8,
  activeDeliveries: 23,
  completedDeliveries: 156,
  averageDeliveryTime: 2.3,
  customerSatisfaction: 4.8,
  returnRate: 2.1,
};
